# Generated by Django 4.0.4 on 2022-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='commentimg',
            field=models.ImageField(default='./static/img/user.png', upload_to=''),
        ),
    ]
