# Generated by Django 4.0.4 on 2022-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogcomment_commentimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='commentimg',
        ),
    ]
