# Generated by Django 4.0.4 on 2022-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('emai', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
